"""Diverse text samples for Pythia-70M analysis. 30 samples across 6 domains."""

SAMPLE_LABELS = (
    ["news"] * 5 + ["technical"] * 5 + ["code"] * 5 +
    ["dialogue"] * 5 + ["fiction"] * 5 + ["repetitive"] * 5
)

TEXT_SAMPLES = [
    # === NEWS (5) ===
    "The European Union announced new regulations on artificial intelligence on Tuesday, requiring companies to disclose when content is generated by AI systems. The legislation, which passed with broad support in the European Parliament, will take effect in 2027. Technology companies have expressed concerns about compliance costs, while consumer advocates praised the move as a necessary step toward transparency.",

    "Hurricane Maria made landfall along the Gulf Coast early Wednesday morning, bringing sustained winds of 120 miles per hour and heavy rainfall. Emergency officials urged residents in low-lying areas to evacuate immediately. The storm is expected to weaken as it moves inland, but flooding remains a serious concern for communities along major river systems throughout the region.",

    "Global stock markets fell sharply on Monday after the Federal Reserve signaled it would keep interest rates higher for longer than expected. The S&P 500 dropped 2.3 percent, while the Nasdaq Composite fell 3.1 percent. Bond yields rose to their highest levels in over a decade, putting pressure on growth stocks and technology companies that rely on cheap borrowing costs.",

    "Scientists at the Max Planck Institute have discovered a new species of deep-sea fish living near hydrothermal vents in the Pacific Ocean. The creature, which measures approximately 15 centimeters in length, has evolved bioluminescent organs that allow it to communicate with others of its kind in the complete darkness of the ocean floor at depths exceeding 3,000 meters.",

    "The World Health Organization reported that global measles cases increased by 30 percent last year, driven largely by declining vaccination rates in several regions. Africa and Southeast Asia were the hardest hit, with outbreaks affecting millions of children. Health officials warned that the trend could reverse decades of progress in eliminating the disease.",

    # === TECHNICAL (5) ===
    "The transformer architecture consists of an encoder and decoder, each built from stacked layers of multi-head self-attention and feed-forward neural networks. In the attention mechanism, queries, keys, and values are computed from the input embeddings through learned linear projections. The attention scores are calculated as the scaled dot product of queries and keys, then used to weight the values.",

    "Photosynthesis occurs in two main stages: the light-dependent reactions and the Calvin cycle. In the light reactions, chlorophyll absorbs photons and uses their energy to split water molecules, releasing oxygen and generating ATP and NADPH. These energy carriers then drive the Calvin cycle, where carbon dioxide is fixed into glucose through a series of enzyme-catalyzed reactions.",

    "In thermodynamics, entropy is a measure of the disorder or randomness of a system. The second law states that the total entropy of an isolated system can only increase over time. This principle explains why heat flows spontaneously from hot objects to cold ones, why gases expand to fill their containers, and why certain chemical reactions proceed in only one direction.",

    "The fast Fourier transform reduces the computational complexity of computing the discrete Fourier transform from O(n squared) to O(n log n). The algorithm works by recursively decomposing the DFT of size n into two DFTs of size n/2, exploiting the periodicity and symmetry properties of the complex exponential basis functions. This makes spectral analysis practical for large datasets.",

    "Mitosis is the process by which a single cell divides to produce two genetically identical daughter cells. It proceeds through four phases: prophase, where chromosomes condense and the nuclear envelope breaks down; metaphase, where chromosomes align at the cell's equator; anaphase, where sister chromatids separate and move to opposite poles; and telophase, where new nuclear envelopes form.",

    # === CODE (5) ===
    'def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1',

    'class LinkedList:\n    def __init__(self):\n        self.head = None\n    def append(self, value):\n        node = Node(value)\n        if not self.head:\n            self.head = node\n            return\n        current = self.head\n        while current.next:\n            current = current.next\n        current.next = node',

    'import numpy as np\nimport matplotlib.pyplot as plt\n\nx = np.linspace(0, 2 * np.pi, 100)\ny = np.sin(x)\nplt.figure(figsize=(10, 6))\nplt.plot(x, y, label="sin(x)")\nplt.xlabel("x")\nplt.ylabel("y")\nplt.title("Sine Wave")\nplt.legend()\nplt.grid(True)\nplt.show()',

    'SELECT customers.name, orders.total\nFROM customers\nINNER JOIN orders ON customers.id = orders.customer_id\nWHERE orders.total > 100\nGROUP BY customers.name\nHAVING COUNT(orders.id) > 3\nORDER BY orders.total DESC\nLIMIT 10;',

    'async function fetchData(url) {\n    try {\n        const response = await fetch(url);\n        if (!response.ok) {\n            throw new Error(`HTTP error: ${response.status}`);\n        }\n        const data = await response.json();\n        return data;\n    } catch (error) {\n        console.error("Failed to fetch:", error);\n        return null;\n    }\n}',

    # === DIALOGUE (5) ===
    '"What do you think about the new policy?" asked Sarah, leaning back in her chair. "I think it\'s a step in the right direction," replied Tom, "but there are still some issues we need to address. The timeline is too aggressive, and we don\'t have enough resources." Sarah nodded. "I agree about the resources. Let me talk to the budget committee about that."',

    "Q: How do I fix a memory leak in my Python application?\nA: First, use a profiler like memory_profiler or tracemalloc to identify where memory is growing. Common causes include circular references, global caches that grow unbounded, and forgotten event listeners. Once you find the leak, you can fix it by breaking circular references, adding cache eviction policies, or properly cleaning up resources.",

    'User: Can you help me understand recursion?\nAssistant: Sure! Recursion is when a function calls itself to solve a smaller version of the same problem. Think of it like Russian nesting dolls - each doll contains a smaller version of itself. You need two things: a base case that stops the recursion, and a recursive case that breaks the problem down.',

    "Interviewer: Tell me about your experience with distributed systems.\nCandidate: I spent three years building microservices at my previous company. We migrated from a monolithic architecture to about forty services. The biggest challenges were managing network failures, maintaining data consistency across services, and debugging issues that spanned multiple systems.",

    '"I don\'t understand why the tests are failing," said Alex, staring at the screen. "Did you check the database connection?" asked Jordan. "It was working yesterday." Alex scrolled through the logs. "Wait, I see it now. The connection string is pointing to the staging database instead of the test database. Someone must have changed the config."',

    # === FICTION (5) ===
    "The old lighthouse keeper climbed the spiral staircase for the last time, his weathered hands gripping the iron railing. Forty years he had tended this light, watching storms roll in from the Atlantic and guiding ships safely past the rocky shoals. Tomorrow, the automated system would take over, and he would have no reason to climb these stairs again.",

    "Rain hammered against the windows of the detective's office as she spread the photographs across her desk. Three victims, three different neighborhoods, but the same calling card left at each scene: a single white orchid placed on the doorstep. She picked up the phone and dialed the forensics lab. Something about those flowers didn't add up.",

    "The spaceship emerged from hyperspace into a field of debris. Captain Torres gripped the armrests of her command chair as alarms blared throughout the bridge. \"Shields up!\" she ordered. \"What happened here?\" The navigation officer's voice was steady but strained. \"Based on the debris signatures, this was a fleet of cargo vessels. They were destroyed within the last twelve hours.\"",

    "She found the letter tucked inside a book she hadn't opened in years. The paper was yellowed and fragile, the ink faded but still legible. It was from her grandmother, written the year before she died. As she read the words, memories flooded back: summer afternoons in the garden, the smell of lavender, and stories told in a gentle voice that she would never hear again.",

    "The market was alive with color and noise. Vendors called out prices for spices and silk, their voices competing with the bleating of goats and the clatter of cart wheels on cobblestone. Marcus pushed through the crowd, keeping one hand on his coin purse and the other on the map he had drawn from memory. The meeting point was just ahead, past the fountain.",

    # === REPETITIVE/STRUCTURED (5) ===
    "The cat sat on the mat. The dog sat on the log. The cat sat on the mat. The dog sat on the log. The cat chased the dog. The dog chased the cat. The cat sat on the mat again. The dog sat on the log again.",

    "Step 1: Preheat the oven to 350 degrees. Step 2: Mix the flour, sugar, and eggs in a large bowl. Step 3: Add the butter and milk. Step 4: Pour the batter into the pan. Step 5: Bake for 30 minutes. Step 6: Let it cool for 10 minutes. Step 7: Serve with cream.",

    "Monday is the first day of the week. Tuesday is the second day of the week. Wednesday is the third day of the week. Thursday is the fourth day of the week. Friday is the fifth day of the week. Saturday is the sixth day of the week. Sunday is the seventh day of the week.",

    "Alice went to the store. Bob went to the park. Alice bought some apples. Bob found a bench. Alice went to the park. Bob went to the store. Alice found a bench. Bob bought some oranges. Alice went home. Bob went home.",

    "The quick brown fox jumps over the lazy dog. A quick brown fox jumped over a lazy dog. The quick brown fox jumps over the lazy dog again. Another quick brown fox jumps over another lazy dog. The fox is quick and brown. The dog is lazy.",
]

assert len(TEXT_SAMPLES) == 30
assert len(SAMPLE_LABELS) == 30
